export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';

export const FETCH_SERVICE_VIEW_REQUEST = 'FETCH_SERVICE_VIEW_REQUEST';
export const FETCH_SERVICE_VIEW_FAILURE = 'FETCH_SERVICE_VIEW_FAILURE';
export const FETCH_SERVICE_VIEW_SUCCESS = 'FETCH_SERVICE_VIEW_SUCCESS';
