export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const REMOVE_SERVICE_REQUEST = 'REMOVE_SERVICE_REQUEST';
export const REMOVE_SERVICE_FAILURE = 'REMOVE_SERVICE_FAILURE';
export const REMOVE_SERVICE_SUCCESS = 'REMOVE_SERVICE_SUCCESS';

export const EDIT_SERVICE_REQUEST = 'EDIT_SERVICE_REQUEST';
export const EDIT_SERVICE_FAILURE = 'EDIT_SERVICE_FAILURE';
export const EDIT_SERVICE_SUCCESS = 'EDIT_SERVICE_SUCCESS';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const CLEAR_SERVICE_ADD = 'CLEAR_SERVICE_FIELD';
export const FETCH_EDIT_SERVICE_REQUEST = 'FETCH_EDIT_SERVICE_REQUEST';
export const FETCH_EDIT_SERVICE_FAILURE = 'FETCH_EDIT_SERVICE_FAILURE';
export const FETCH_EDIT_SERVICE_SUCCESS = 'FETCH_EDIT_SERVICE_SUCCESS';